### ISSUE TITLE
BUG: Windows env throws error 

### ISSUE THREAD

**Issue by markoprodanovic** [saud-learning-services/cleaning-zoom-polls#1]
![IMG_0556](https://user-images.githubusercontent.com/22332030/92813005-3d191a80-f375-11ea-9da6-0ea516d4aebe.jpg)

Mac ran successfully.
Only had the issue via Windows.

Let me know if you want a hand debugging since I have access to a PC

**Comment by markoprodanovic** [comment]
@alisonmyers 
The issue is in **line 153**
```python
f_name = re.search(r"poll_input\/(.*)\.csv", f, re.IGNORECASE).group(1)
```

Windows doesn't play nice with forward slash "/" characters for file paths

If I change it to backslash:
```python
f_name = re.search(r"poll_input\\(.*)\.csv", f, re.IGNORECASE).group(1)
```
...it runs but probably would create the same kind of issue on Mac

Here's another way we could consider iterating through the CSV files in the `poll_input` directory:
https://stackoverflow.com/questions/10377998/how-can-i-iterate-over-files-in-a-given-directory

**Comment by markoprodanovic** [comment]
Btw I could implement this fix, just thought you may want to know what's going on :)
Let me know!

**Comment by alisonmyers** [comment]
OR could use glob

```
import glob
print(glob.glob("/poll_input/*.csv"))
```
don't know why I went the re route !

**Comment by markoprodanovic** [comment]
Ooo didn't know about that library. Even better!

**Comment by alisonmyers** [comment]
oh wait, misunderstanding this. 
All we need is a parser for the filename that is added as a column (I use glob to read in the files already)

**Comment by alisonmyers** [comment]
As discussed, I think problem is that windows paths are different from mac, so the regex is looking for a match that doesn't exist. So, I think this would work:

`f_name = re.search(r"poll_input(\/|\\)(.*)\.csv", f, re.IGNORECASE).group(2)`

- creates a second match group (either / or \)
- now we get group(2) instead of group(1)

Works on a mac.
